name: pensil_community_flutter
description: The official dart package to create your own community powered by Pensil.
version: 0.1.2
repository: https://github.com/pensil-inc/pensil-community-flutter/tree/main/packages/pensil_community_flutter
issue_tracker: https://github.com/pensil-inc/pensil-community-flutter/issues
homepage: https://pensil.in/

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations: ^2.0.2
  timeago: ^3.1.0
  photo_view: ^0.13.0
  flutter_svg: ^1.0.0
  flutter_markdown: ^0.6.9
  cached_network_image: ^3.2.0
  
  dartz: ^0.10.1
  collection: ^1.15.0

  # Data class generator
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  freezed: ^1.1.0

  file_picker: ^4.3.1
  image_picker: ^0.8.4+4
  video_player: ^2.2.10
  chewie: ^1.2.2
  url_launcher: ^6.0.17
  permission_handler: ^8.3.0
 
  rxdart: ^0.27.3
  html: ^0.15.0
  http: ^0.13.4
  string_scanner: ^1.1.0

  pensil_community_core: ^0.1.1+2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3

flutter:

  assets:
    - lib/assets/
    - lib/assets/icon/
    - lib/assets/pensil_icon_font.ttf


  fonts:
    - family: PensilIcon
      fonts:
        - asset: lib/assets/pensil_icon_font.ttf

