name: pensil_community_core
description: Pensil community official Dart SDK. Build your own community experience using Dart and Flutter.
version: 0.1.1+1
repository: https://github.com/pensil-inc/pensil-community-flutter/tree/main/packages/pensil_community_core
issue_tracker: https://github.com/pensil-inc/pensil-community-flutter/issues
homepage: https://pensil.in/

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  intl: ^0.17.0
  dartz: ^0.10.1
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  freezed: ^1.1.0
  rxdart: ^0.27.3
  logging: ^1.0.2
  injectable: ^1.5.0
  get_it: ^7.2.0
  connectivity_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3

flutter: